### ISSUE TITLE
ERROR: a 'NAMESPACE' file is required

### ISSUE THREAD

**Issue by thecurlyhound** [phubers/erlang#1]
Hi there
I just tried to install your package on R3.4.3 and got the namespace error. Could you please let me know what I missed? I've installed roxygen2 as well. Thank you. 
>  devtools::install_github("phubers/erlang")
Downloading GitHub repo phubers/erlang@master
from URL https://api.github.com/repos/phubers/erlang/zipball/master
Installing Erlang
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Amelia/AppData/Local/Temp/RtmpaGW5zX/devtools1428c9a31a0/phubers-erlang-c4f1ea4"  \
  --library="C:/Users/Amelia/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'Erlang' ...
ERROR: a 'NAMESPACE' file is required
* removing 'C:/Users/Amelia/Documents/R/win-library/3.4/Erlang'
In R CMD INSTALL
Installation failed: Command failed (1)

Amelia

**Comment by phubers** [comment]
Sorry for the late reply, I did not (yet) expect anybody to actually use this package. I'll add the namespace file to the repository.

**Comment by phubers** [comment]
Sorry, NAMESPACE is generated when you run roxygen2 when building the package; generated files are not included in the repository. If you're using RStudio, use the option "Document" in the Build menu.
