### ISSUE TITLE
Does it work in R Version 3.5.1?

### ISSUE THREAD

**Issue by Roctober92** [phubers/erlang#5]
Is it published yet? Or does it simply not exist in the recently updated versions of R?

When I run `install.packages("Erlang")`, it says it's not available.

**Comment by phubers** [comment]
I'm currently preparing it for submission to CRAN. If everything goes well, it should be available soon. Otherwise you'll need to install from Github yourself.

**Comment by knightofdan** [comment]
Trying to install this after downloading from Github and get the following error when I run:

> library(erlang-master)
Error in library(erlang - master) : 'package' must be of length 1

I am using R version 3.6.1 and have not been able to find an answer or solution.
