### ISSUE TITLE
avg_wait_time returns a negative value when traffic intensity is greater than number of agents

### ISSUE THREAD

**Issue by trentryan** [phubers/erlang#7]
Example

avg_wait_time(14.01,44.34,646,30)

**Comment by phubers** [comment]
That is correct, because the queue will increase when there is more traffic than available agents. This means that customers will *not* be served. You could use the negative return value to indicate an insufficient number of agents in your code.

**Comment by trentryan** [comment]
Yeah, it makes sense. I suppose it's just a limitation of not having an abandonment rate modeled with erlang.
